services:
  web:
    build: .
    container_name: school_crm
    restart: always
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --no-input &&
        gunicorn -b 0.0.0.0:8000 config.wsgi:application --workers 3 --timeout 300 --log-level INFO
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: school_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: school_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
