# Generated by Django 5.1.7 on 2025-03-14 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('hired_date', models.DateField(verbose_name='Ishga olingan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Rahbarlik',
                'verbose_name_plural': 'Rahbarlar',
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Rasm')),
                ('hired_date', models.DateField(verbose_name='Ishga olingan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Maktab xodimi',
                'verbose_name_plural': 'Maktab xodimlari',
            },
        ),
    ]
