# Generated by Django 5.1.7 on 2025-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('hired_date', models.DateField(verbose_name='Ishga olingan sana')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbarlar',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='Sinf')),
                ('shift', models.IntegerField(choices=[(1, 'Birinchi navbat'), (2, 'Ikkinchi navbat')], default=1, verbose_name='Smena')),
                ('weekday', models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba')], max_length=10, verbose_name='Hafta kuni')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='schoolStaff_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(null=True, verbose_name="Ma'lumotnoma")),
                ('hired_date', models.DateField(verbose_name='Ishga olingan sana')),
            ],
            options={
                'verbose_name': 'Maktab xodimi',
                'verbose_name_plural': 'Maktab xodimlari',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism-sharifi')),
                ('grade', models.IntegerField(verbose_name='Sinf')),
                ('birth_date', models.DateField(max_length=20, verbose_name="Tug'ilgan sanasi")),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Fan nomi')),
                ('grades', models.CharField(max_length=20, verbose_name='Qaysi sinflarga')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name="Ma'lumotnoma")),
                ('hired_date', models.DateField(verbose_name='Qabul qilingan sana')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
    ]
