# Generated by Django 5.1.7 on 2025-03-15 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_alter_schoolstaff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism-sharifi')),
                ('grade', models.IntegerField(verbose_name='Sinf')),
                ('birth_date', models.DateField(max_length=20, verbose_name="Tug'ilgan sanasi")),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Rahbar', 'verbose_name_plural': 'Rahbarlar'},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(upload_to='teacher_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name="Ma'lumotnoma")),
                ('hired_date', models.DateField(verbose_name='Qabul qilingan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Fan-O'qituvchi",
                'verbose_name_plural': "Fan-O'qituvchilar",
                'unique_together': {('subject', 'teacher')},
            },
        ),
    ]
