# Generated by Django 5.1.7 on 2025-03-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grades',
        ),
    ]
