# Generated by Django 5.1.7 on 2025-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_student_subject_alter_leadership_options_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schoolStaff_photos/', verbose_name='Rasm'),
        ),
    ]
