# Generated by Django 5.1.7 on 2025-03-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_remove_subject_grades'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_grade_weekday',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subject_list', to='school_management.teacher', verbose_name="O'qituvchi(lar)"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba')], max_length=10, verbose_name='Hafta kuni'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('grade',)},
        ),
    ]
