# Generated by Django 5.1.7 on 2025-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_alter_schoolstaff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='bio',
            field=models.TextField(null=True, verbose_name="Ma'lumotnoma"),
        ),
    ]
