# Generated by Django 5.1.7 on 2025-03-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_remove_schedule_unique_grade_weekday_subject_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
