# Generated by Django 5.1.7 on 2025-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_schoolstaff_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.CharField(default=1, max_length=20, verbose_name='Qaysi sinflarga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='school_management.subject', verbose_name='Fan(lar)i'),
        ),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
