# Generated by Django 5.1.7 on 2025-03-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_remove_schedule_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
