# Generated by Django 5.1.7 on 2025-03-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_remove_subject_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
