# Generated by Django 5.1.7 on 2025-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_subject_grades_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Rasm'),
        ),
    ]
