# Generated by Django 5.1.7 on 2025-03-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.IntegerField(choices=[(1, 'Birinchi navbat'), (2, 'Ikkinchi navbat')], default=1, verbose_name='Smena')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('break_time', models.CharField(default='5 daqiqa', max_length=20, verbose_name='Tanaffus vaqti')),
            ],
            options={
                'verbose_name': 'Dars jadvali vaqti',
                'verbose_name_plural': 'Dars jadvali vaqtlari',
            },
        ),
    ]
