# Generated by Django 5.1.7 on 2025-03-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('full_name', 'birth_date')},
        ),
    ]
