# Generated by Django 5.1.7 on 2025-03-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_bellschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='To‘garak nomi')),
                ('weekday', models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba')], max_length=10, verbose_name='Hafta kuni')),
                ('grades', models.CharField(max_length=20, verbose_name='Sinflar')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('students', models.IntegerField(verbose_name="O'quvchilar soni")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_schedules', to='school_management.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name_plural': 'To‘garak jadvallari',
            },
        ),
    ]
