# Generated by Django 5.1.7 on 2025-03-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0009_clubschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubschedule',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='club_schedules', to='school_management.subject', verbose_name='Fani'),
            preserve_default=False,
        ),
    ]
