# Generated by Django 5.1.7 on 2025-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_clubschedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubschedule',
            name='weekday',
            field=models.CharField(max_length=50, verbose_name='Hafta kuni'),
        ),
    ]
