# Generated by Django 5.1.7 on 2025-03-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0011_alter_clubschedule_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tadbir nomi')),
                ('date', models.DateField(verbose_name='Tadbir sanasi')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/', verbose_name='Rasm')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='school_management.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir surati',
                'verbose_name_plural': 'Tadbir suratlari',
            },
        ),
    ]
