# Generated by Django 5.1.7 on 2025-03-23 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0012_event_eventphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tadbir sanasi'),
        ),
    ]
