# Generated by Django 5.1.7 on 2025-03-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphoto',
            old_name='image',
            new_name='photos',
        ),
    ]
