# Generated by Django 5.1.7 on 2025-03-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0014_rename_image_eventphoto_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(verbose_name='Sinf'),
        ),
    ]
