# Generated by Django 5.1.7 on 2025-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0015_alter_student_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('full_name',)},
        ),
    ]
