# Generated by Django 5.1.7 on 2025-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0016_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1A', '1-A'), ('1B', '1-B'), ('2A', '2-A'), ('2B', '2-B'), ('3A', '3-A'), ('3B', '3-B'), ('4A', '4-A'), ('4B', '4-B'), ('5A', '5-A'), ('5B', '5-B'), ('6A', '6-A'), ('6B', '6-B'), ('7A', '7-A'), ('7B', '7-B'), ('8A', '8-A'), ('8B', '8-B'), ('9A', '9-A'), ('9B', '9-B'), ('10A', '10-A'), ('10B', '10-B'), ('11A', '11-A'), ('11B', '11-B')], verbose_name='Sinf'),
        ),
    ]
