name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: school_db
          POSTGRES_USER: school_admin
          POSTGRES_PASSWORD: admin_pass
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U school_admin" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_DB: school_db
      POSTGRES_USER: school_admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U school_admin; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Run tests
        run: python manage.py test
